language: node_js
version: 1.0
node_js:
- node
cache: npm
script:
- "./bin/run --version"
- "./bin/run --help"
- npm run test
deploy:
  provider: npm
  email: benzhangniu@hotmail.com
  api_key:
    secure: mN2Mjf7Px7VY/RPKb1faIdVJLzppBQ0ESyBE8yK2vDtUjqxc8kVRO7xiAr66oD8BSaxUiIy1o9uUgnzvn5fq9mmPG0pnzWwRAJdJpHVT2i2hwecIs7ZayY6YmN5Nw7tBZtq2zPXN8OwEVCYSRY0pW/LsbBvTH0eQZznkzhfGgJUCNcSLy8Lqy3yC433GEEsc/JearZ4gARAWymjkfXaMIpXdMrSF6DS+/rUtwMlLpE3kbiZ/XaDGFAjqudzOLNnijYAu9deWURjfVNnpbKp3wESCfIcQnkSgKcqjOz1tIISbenw2xTRTiYsADCwD423OwfnSEgWvRbUUw8lgU2RJG//xw1poWEHxZylmo40ts0T8qIQJJlyXcgwhJU+AXajSCi/VAIzjRN+FnLlrSIXvp0o569uSRW+tboF1NnJMpCnK7r5YAncsnteOLSP7TX0Zneyi3PE6WfIOk48yf0WC7ZBTiNZocBZj9QHYiWN87/ztNlkaii3Q1DVAfCTZLVH8RozNvzWvvQu0CdbriCF7DQfkBlEsO5A4cbRlNxcuVAHVb88XEXDCHc/35z+lZqt0WYtSW3sxlCdhNecPazJHddA7NaHNBWYArv6OC7Sg/QJmBuVy/NiZn10rBvaV343jUX5/9lqkOWc0HrlWRDNAEBPbW9i1Hna4tUm2vMIC6Qk=
  on:
    tags: true
    repo: Unicorns/rainbows
