name: Build & Publish

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
    - name: Compile TS to JS
      run: tsc -b
    - name: Publish to NPM
      run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
