name: Test & Build & Publish

on:
  release:
    types: [published]

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm run test
    - name: Publish to Github Package Registry
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PUBLISH_TOKEN }}
