name: Test & Build

on: [push]

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        ./bin/run --version
        ./bin/run --help
        npm run test
    - name: Compile TS to JS
      run: tsc -b
