name: Test & Build & Publish

on:
  release:
    types: [published]

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm run test
    - name: Publish to Github Package Registry
      run: |
        npm set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
        npm login
        npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PUBLISH_TOKEN }}
