name: Test & Build & Publish Tags

on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: |
        ./bin/run --version
        ./bin/run --help
        npm run test
    - name: Publish to Github Package Registry
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        # rainbows -> @unicorns/rainbows
        awk 'NR==1,/"name": "rainbows"/{sub(/"name": "rainbows"/, "\"name\": \"@unicorns/rainbows\"")} 1' package.json > package.json.new
        mv package.json.new package.json
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check if compilable (if publish did not execute)
      if: (! startsWith(github.ref, 'refs/tags/v'))
      run: tsc -b

